[package]
name = "iv"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
lazy_static = "1.5.0"
logos = "0.14.0"
regex = "1.11.1"
